FROM default-route-openshift-image-registry.apps.ocpdev.shinhan.com/gap-cagent-dev/gaf-base-serving-py312:0.0.3
ARG NEXUS_URL_HOST
ARG NEXUS_URL
ARG SHBMCP_SERVER_NAME

ENV PIP_TRUSTED_HOST=$NEXUS_URL_HOST
ENV PIP_INDEX_URL=$NEXUS_URL
ENV SHBMCP_SERVER_NAME=$SHBMCP_SERVER_NAME

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]